const roles=[
 {id:'worker',icon:'👷',name:'แรงงาน',color:'#a9b2bf',cls:'ประชาชน',desc:'รับงานง่าย รายได้สม่ำเสมอ ไม่ต้องลงทุนมาก'},
 {id:'farmer',icon:'🌱',name:'เกษตรกร',color:'#58d68d',cls:'ผู้ประกอบอาชีพ',desc:'ผลิตวัตถุดิบต้นน้ำและขายให้ธุรกิจอื่น'},
 {id:'craft',icon:'🛠️',name:'ช่างฝีมือ',color:'#6ea8ff',cls:'ผู้ประกอบอาชีพ',desc:'สร้าง ซ่อม และดูแลอุปกรณ์ของผู้เล่น'},
 {id:'maker',icon:'🏭',name:'ผู้ผลิต',color:'#718cff',cls:'ผู้ประกอบอาชีพ',desc:'แปรรูปวัตถุดิบให้กลายเป็นสินค้ามูลค่าสูง'},
 {id:'merchant',icon:'🛒',name:'พ่อค้า',color:'#ffad66',cls:'ผู้ประกอบการ',desc:'ซื้อขาย ตั้งราคา และสร้างกำไรจากตลาด'},
 {id:'logistics',icon:'🚚',name:'ขนส่ง',color:'#62d6e8',cls:'ผู้ประกอบอาชีพ',desc:'เชื่อมผู้ผลิต ร้านค้า และลูกค้าด้วยงานขนส่ง'},
 {id:'service',icon:'🍽️',name:'บริการ',color:'#ff8fd1',cls:'ผู้ประกอบอาชีพ',desc:'สร้างรายได้จากร้านอาหาร คาเฟ่ ที่พัก และบริการ'},
 {id:'freelance',icon:'💼',name:'ฟรีแลนซ์',color:'#55d6be',cls:'ประชาชน',desc:'รับ Contract ได้หลายสายโดยไม่ต้องสังกัดบริษัท'},
 {id:'creator',icon:'🎨',name:'ครีเอเตอร์',color:'#b78cff',cls:'ประชาชน',desc:'สร้างชื่อเสียง ผู้ติดตาม ผลงาน และรายได้จากสังคม'}
];
const initialMessages={
 'ทั่วไป':[
  {u:'Alice',c:'#b78cff',a:'A',role:'นักธุรกิจ',cls:'ชนชั้นธุรกิจ',rep:'4.93',t:'11:58',m:'ตลาดวันนี้คึกคักมาก มีร้านใหม่เปิดตรง ACC Plaza ด้วย ✨'},
  {u:'Rin',c:'#58d68d',a:'R',role:'เกษตรกร',cls:'ผู้ประกอบอาชีพ',rep:'4.72',t:'12:01',m:'ล็อตผักรอบเที่ยงลงตลาดแล้วนะ ใครทำร้านอาหารดูได้เลย 🌱'},
  {u:'Kansai',c:'#62d6e8',a:'K',role:'ฟรีแลนซ์',cls:'ประชาชน',rep:'4.51',t:'12:04',m:'รับงานออกแบบป้ายร้าน 2 คิวค่ะ ส่งรายละเอียด DM ได้เลย'}
 ],
 'ตลาด':[{u:'Market Bot',c:'#ffc857',a:'฿',role:'ระบบตลาด',cls:'เมือง',rep:'—',t:'12:00',m:'ราคาวัตถุดิบอาหารเฉลี่ยเพิ่มขึ้น 3.2% ในช่วง 1 ชั่วโมงที่ผ่านมา'}],
 'หางาน':[{u:'Nova Foods',c:'#718cff',a:'N',role:'บริษัท',cls:'ชนชั้นธุรกิจ',rep:'4.88',t:'11:49',m:'เปิดรับผู้ช่วยสายการผลิต 4 ตำแหน่ง ค่าจ้าง ฿420 / รอบ'}],
 'โรลเพลย์':[{u:'Ado',c:'#ff8fd1',a:'A',role:'ครีเอเตอร์',cls:'ผู้ประกอบอาชีพ',rep:'4.90',t:'11:40',m:'[IC] เดินเข้ามาที่ Plaza พร้อมกาแฟหนึ่งแก้ว ก่อนนั่งลงตรงม้านั่งริมถนน'}],
 'ข่าวเมือง':[{u:'ACC News',c:'#ffc857',a:'N',role:'นักข่าว',cls:'เมือง',rep:'4.96',t:'11:30',m:'เทศบาลประกาศเปิดเขตตลาดกลางใหม่ ทดลองลดค่าธรรมเนียมการขาย 20% วันนี้'}]
};
let selectedRole='merchant', activeRole='merchant', userName='Miyako', uid='', currentChannel='ทั่วไป', currentView='chat', casinoBalance=12450, workSeconds=1302;
const rate={THB:1,JPY:4.25,USD:0.028,KRW:38.4};const symbols={THB:'฿',JPY:'¥',USD:'$',KRW:'₩'};let currency='THB';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>el.classList.remove('show'),1800)}
function code(){return 'ACC-GUEST-'+Math.random().toString(36).slice(2,6).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function setTab(tab){const guest=tab==='guest';$('#guestTab').classList.toggle('active',guest);$('#normalTab').classList.toggle('active',!guest);$('#guestForm').classList.toggle('hidden',!guest);$('#normalForm').classList.toggle('hidden',guest)}
$('#guestTab').addEventListener('click',()=>setTab('guest'));$('#normalTab').addEventListener('click',()=>setTab('normal'));
$('#normalLogin').addEventListener('click',()=>toast('UI พร้อมแล้ว — Auth จริงจะเชื่อมในขั้นฐานข้อมูล'));
function openRolePicker(){const grid=$('#roleGrid');grid.innerHTML=roles.map(r=>`<button type="button" class="role-card ${r.id===selectedRole?'selected':''}" data-role="${r.id}" style="--role:${r.color}"><strong><span class="role-swatch" style="background:${r.color}"></span>${r.icon} ${r.name}</strong><div class="tiny muted">ฐานะเริ่มต้น: ${r.cls}</div><div class="small" style="margin-top:7px;color:#cbd8e9">${r.desc}</div></button>`).join('');grid.querySelectorAll('.role-card').forEach(b=>b.addEventListener('click',()=>{selectedRole=b.dataset.role;openRolePicker()}));$('#rolePicker').classList.remove('hidden')}
$('#guestStart').addEventListener('click',()=>{userName=$('#guestName').value.trim()||'Guest';uid=code();openRolePicker()});
$('#transferBtn').addEventListener('click',()=>{const v=$('#transferInput').value.trim();if(v.length<8){toast('ใส่ UID / Transfer Code ก่อนนะ');return}userName='Returning Guest';uid=v;openRolePicker()});
$('#confirmRole').addEventListener('click',()=>{activeRole=selectedRole;$('#rolePicker').classList.add('hidden');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');updateUser();renderChats();renderRoles();updateMoney();toast('ยินดีต้อนรับสู่ ACC City')});
function roleObj(id=activeRole){return roles.find(r=>r.id===id)||roles[0]}
function updateUser(){const r=roleObj();document.documentElement.style.setProperty('--role',r.color);$('#profileName').textContent=userName;$('#mProfileName').textContent=userName;$('#uidText').textContent=uid;$('#activeRoleTop').textContent=`${r.icon} ${r.name}`;$('#mActiveRole').textContent=`${r.icon} ${r.name}`;$('#mRoleLine').textContent=`${r.icon} ${r.name}`;$$('.profile-avatar,.m-avatar').forEach(el=>el.textContent=userName.charAt(0).toUpperCase())}
function renderRoles(){const owned=[activeRole,'worker'].filter((v,i,a)=>a.indexOf(v)===i);$('#roleCount').textContent=owned.length;$('#roleChips').innerHTML=owned.map(id=>{const r=roleObj(id);return `<div class="role-chip ${id===activeRole?'active':''}" style="border-color:${id===activeRole?r.color:''}"><span><span class="role-swatch" style="background:${r.color}"></span>${r.icon} ${r.name}</span><button data-activate="${id}" ${id===activeRole?'disabled':''}>${id===activeRole?'ใช้งานอยู่':'ใช้สีนี้'}</button></div>`}).join('');$('#mRoleList').innerHTML=owned.map(id=>{const r=roleObj(id);return `<div class="m-menu-card"><div class="row"><span style="color:${r.color}">${r.icon} <b>${r.name}</b></span><span class="tiny muted">${id===activeRole?'Active':'สะสมแล้ว'}</span></div></div>`}).join('');$$('[data-activate]').forEach(b=>b.addEventListener('click',()=>{activeRole=b.dataset.activate;updateUser();renderRoles();renderChats();toast('เปลี่ยน Active Role แล้ว')}))}
function renderChats(){const msgs=initialMessages[currentChannel]||[];const render=(m,mobile=false)=>`<div class="${mobile?'m-chat-message':'message'}"><div class="avatar">${m.a}</div><div><div class="message-head"><span class="username" style="color:${m.c}">${m.u}</span><span class="badge">${m.cls}</span><span class="rep">★ ${m.rep}</span><span class="time">${m.t}</span></div><div class="message-body">${m.m}</div></div></div>`;$('#chatList').innerHTML=msgs.map(m=>render(m)).join('');$('#mChatList').innerHTML=msgs.map(m=>render(m,true)).join('')}
function sendMessage(input){const text=input.value.trim();if(!text)return;const r=roleObj();(initialMessages[currentChannel]||(initialMessages[currentChannel]=[])).push({u:userName,c:r.color,a:userName.charAt(0).toUpperCase(),role:r.name,cls:'ผู้ประกอบอาชีพ',rep:'4.82',t:new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}),m:text.replace(/[<>]/g,'')});input.value='';renderChats()}
$('#sendChat').addEventListener('click',()=>sendMessage($('#chatInput')));$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendMessage(e.currentTarget)});$('#mSendChat').addEventListener('click',()=>sendMessage($('#mChatInput')));$('#mChatInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendMessage(e.currentTarget)});
$$('.chat-channel').forEach(b=>b.addEventListener('click',()=>{currentChannel=b.dataset.channel;$$('.chat-channel').forEach(x=>x.classList.toggle('active',x===b));$('#desktopViewTitle').textContent=currentChannel;$('#chatInput').placeholder=`ส่งข้อความใน #${currentChannel}`;setView('chat');renderChats()}));
function setView(v){currentView=v;$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$$('.nav-view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#desktopCompose').classList.toggle('hidden',v!=='chat');const titles={chat:currentChannel,economy:'กระเป๋าเงิน',work:'งาน & การผลิต',market:'ตลาดกลาง',casino:'คาสิโน'};const icons={chat:'#',economy:'฿',work:'▣',market:'◆',casino:'♠'};$('#desktopViewTitle').textContent=titles[v];$('#desktopViewIcon').textContent=icons[v]}
$$('.nav-view').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
function formatTHB(v,cur=currency){const n=v*rate[cur];const decimals=cur==='USD'?2:0;return symbols[cur]+new Intl.NumberFormat(cur==='JPY'?'ja-JP':cur==='USD'?'en-US':cur==='KRW'?'ko-KR':'th-TH',{minimumFractionDigits:decimals,maximumFractionDigits:decimals}).format(n)}
function updateMoney(){$$('.money').forEach(el=>{let v=Number(el.dataset.thb||0);const sign=el.textContent.trim().startsWith('-')?'-':el.textContent.trim().startsWith('+')?'+':'';el.textContent=sign+formatTHB(v)});$('#casinoBalance').textContent=formatTHB(casinoBalance);$('#mCasinoResult').textContent='ยอดทดลอง: '+formatTHB(casinoBalance)}
$('#currency').addEventListener('change',e=>{currency=e.target.value;$('#mCurrency').value=currency;updateMoney()});$('#mCurrency').addEventListener('change',e=>{currency=e.target.value;$('#currency').value=currency;updateMoney()});
function spin(mobile=false){if(casinoBalance<100){toast('ยอดเงินไม่พอ');return}casinoBalance-=100;const icons=['🍒','🍋','⭐','💎','7️⃣'];const picks=[0,1,2].map(()=>icons[Math.floor(Math.random()*icons.length)]);let win=0;if(picks[0]===picks[1]&&picks[1]===picks[2])win=picks[0]==='7️⃣'?1200:picks[0]==='💎'?800:500;else if(picks[0]===picks[1]||picks[1]===picks[2]||picks[0]===picks[2])win=140;casinoBalance+=win;['slot1','slot2','slot3'].forEach((id,i)=>$('#'+id).textContent=picks[i]);['mslot1','mslot2','mslot3'].forEach((id,i)=>$('#'+id).textContent=picks[i]);const msg=win?`ชนะ ${formatTHB(win)} 🎉`:'ไม่ถูกรางวัล — ลองใหม่ได้';$('#casinoResult').innerHTML=`${msg}<br><span class="tiny muted">ยอดทดลอง ${formatTHB(casinoBalance)}</span>`;$('#mCasinoResult').textContent=`${msg} · ${formatTHB(casinoBalance)}`}
$('#spinBtn').addEventListener('click',()=>spin());$('#mSpinBtn').addEventListener('click',()=>spin(true));
$$('.mnav').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.mview;$$('.mnav').forEach(x=>x.classList.toggle('active',x===b));$$('.m-view').forEach(x=>x.classList.toggle('active',x.id===`mview-${v}`))}));$$('.nav-casino').forEach(b=>b.addEventListener('click',()=>{$$('.m-view').forEach(x=>x.classList.toggle('active',x.id==='mview-casino'));$$('.mnav').forEach(x=>x.classList.remove('active'))}));
setInterval(()=>{workSeconds=Math.max(0,workSeconds-1);const h=String(Math.floor(workSeconds/3600)).padStart(2,'0'),m=String(Math.floor(workSeconds%3600/60)).padStart(2,'0'),s=String(workSeconds%60).padStart(2,'0'),v=`${h}:${m}:${s}`;$('#workTimer').textContent=v;$('#mWorkTimer').textContent=v},1000);
renderChats();